apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: efs-logs
              mountPath: /var/log/nginx
      volumes:
        - name: efs-logs
          persistentVolumeClaim:
            claimName: nginx-efs-pvc
