apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-efs-pv
  namespace: prod
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-06ab7a7ac3a9c5325
